# site_name: Omkar Parab
# theme:
#   name: material
#   palette:
#     scheme: slate
#     primary: blue

# nav:
#   - Home: index.md
#   - Projects: projects.md
#   - Experience: experience.md
#   - Contact: contact.md

site_name: Omkar Parab
theme:
  name: material
  features:
    - navigation.tabs: false
    - navigation.sections: false
    - navigation.expand: false
